{"uuid":"50df6c0f-02b3-4154-bdbd-2422e6ea6f54","historyId":"a92d6bfb0467f8e49e8df708bbcc818d","fullName":"Tests.RegisterTest.validateRegisterwithInvalidLastname","labels":[{"name":"package","value":"Tests.RegisterTest"},{"name":"testClass","value":"Tests.RegisterTest"},{"name":"testMethod","value":"validateRegisterwithInvalidLastname"},{"name":"parentSuite","value":"CombinedSuite"},{"name":"suite","value":"Regular TestNG Tests"},{"name":"subSuite","value":"Tests.RegisterTest"},{"name":"host","value":"DESKTOP-6CH6DNR"},{"name":"thread","value":"6084@DESKTOP-6CH6DNR.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"validateRegisterwithInvalidLastname","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The following asserts failed:\n\tWelcome message is not displayed. expected [false] but found [true],\n\tdid not expect [https://awesomeqa.com/ui/index.php?route=account/success] but found [https://awesomeqa.com/ui/index.php?route=account/success]","trace":"java.lang.AssertionError: The following asserts failed:\n\tWelcome message is not displayed. expected [false] but found [true],\n\tdid not expect [https://awesomeqa.com/ui/index.php?route=account/success] but found [https://awesomeqa.com/ui/index.php?route=account/success]\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)\r\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)\r\n\tat Pages.RegisterPage.assertRegisterInvalidName(RegisterPage.java:149)\r\n\tat Tests.RegisterTest.validateRegisterwithInvalidLastname(RegisterTest.java:68)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:829)\r\n\tat org.testng.TestRunner.run(TestRunner.java:602)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\r\n\tat org.testng.TestNG.run(TestNG.java:1067)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1746692233178,"stop":1746692235433}